### ISSUE TITLE
Is this also planed for android?

### ISSUE THREAD

**Issue by yss14** [rajivnarayana/nativescript-toolbar#3]
It would be really cool to have the toolbar feature also on android. Is this planed/possible?
It's very useful to simulate the `ActionBar` in a modal page for example.

**Comment by rajivnarayana** [comment]
I am sure it is possible but it is not currently planned. I would be glad to accept pull requests if you have some time and plan to give the Android part a try.

**Comment by yss14** [comment]
I really want to, but I'm not that much into android development. That's why I'm using NativeScript :) Maybe when I'm more advanced ;)
